from typing import List

from models import Book


def _cover(isbn: str) -> str:
    return f"https://covers.openlibrary.org/b/isbn/{isbn}-L.jpg"


CATALOG: List[Book] = [
    Book(id="b1", title="Ready Player One", author="Ernest Cline",
         price=549, original_price=849, rating=4.7, reviews=42600,
         cover=_cover("0307887448"), category="Sci-Fi", badge="Best Seller",
         description="A virtual treasure hunt inside the OASIS — the ultimate game begins.",
         collection="Editor's Picks", year=2011),
    Book(id="b2", title="A Court of Mist and Fury", author="Sarah J. Maas",
         price=799, original_price=1199, rating=4.9, reviews=21700,
         cover=_cover("1619634465"), category="Romance", badge="Trending",
         description="A sweeping romance and epic fantasy with a fierce heroine.",
         collection="New Releases", year=2016),
    Book(id="b3", title="The Song of Achilles", author="Madeline Miller",
         price=549, original_price=849, rating=4.8, reviews=7200,
         cover=_cover("0062060627"), category="Classics",
         description="A retelling of the Iliad — brutal, beautiful, unforgettable.",
         collection="Award Winners", year=2011),
    Book(id="b4", title="It Ends with Us", author="Colleen Hoover",
         price=499, original_price=799, rating=4.7, reviews=15300,
         cover=_cover("1668001225"), category="Romance",
         description="A story of love, resilience, and difficult choices.",
         collection="New Releases", year=2016),
    Book(id="b5", title="The Hobbit", author="J.R.R. Tolkien",
         price=699, original_price=999, rating=4.9, reviews=45300,
         cover=_cover("054792822X"), category="Fantasy", badge="Classic",
         description="Bilbo's unexpected journey — where every adventure begins.",
         collection="Collector Editions", year=1937),
    Book(id="b6", title="Project Hail Mary", author="Andy Weir",
         price=649, original_price=899, rating=4.9, reviews=18200,
         cover=_cover("0593135202"), category="Sci-Fi", badge="Award Winner",
         description="A lone astronaut must save Earth from disaster.",
         collection="Award Winners", year=2021),
    Book(id="b7", title="Where the Crawdads Sing", author="Delia Owens",
         price=529, original_price=799, rating=4.7, reviews=32100,
         cover=_cover("0735219095"), category="Mystery",
         description="A mystery, coming-of-age story, and celebration of nature.",
         collection="Editor's Picks", year=2018),
    Book(id="b8", title="The Silent Patient", author="Alex Michaelides",
         price=459, original_price=699, rating=4.6, reviews=22400,
         cover=_cover("1250301696"), category="Mystery", badge="Thriller",
         description="A psychological thriller of obsession and silence.",
         collection="New Releases", year=2019),
    Book(id="b9", title="Life of Pi", author="Yann Martel",
         price=479, original_price=699, rating=4.6, reviews=36400,
         cover=_cover("0156027321"), category="Adventure", badge="Award Winner",
         description="A boy, a lifeboat, and a Bengal tiger — 227 days at sea.",
         collection="Award Winners", year=2001),
    Book(id="b10", title="The Seven Husbands of Evelyn Hugo",
         author="Taylor Jenkins Reid", price=629, original_price=899,
         rating=4.9, reviews=41200,
         cover="https://covers.openlibrary.org/b/id/8354226-L.jpg",
         category="Romance", badge="Best Seller",
         description="A reclusive Hollywood icon finally tells her story.",
         collection="Editor's Picks", year=2017),
    Book(id="b11", title="Verity", author="Colleen Hoover",
         price=479, original_price=749, rating=4.7, reviews=28500,
         cover=_cover("1538724731"), category="Horror",
         description="A shocking psychological thriller you won't put down.",
         collection="New Releases", year=2018),
    Book(id="b12", title="Fourth Wing", author="Rebecca Yarros",
         price=749, original_price=1099, rating=4.8, reviews=36700,
         cover=_cover("1649374046"), category="Fantasy", badge="Limited Edition",
         description="Dragons, war college, and a heroine who refuses to break.",
         collection="Limited Editions", year=2023),
    Book(id="b13", title="Dune", author="Frank Herbert",
         price=599, original_price=899, rating=4.8, reviews=52100,
         cover=_cover("0441172717"), category="Sci-Fi", badge="Classic",
         description="Epic saga of politics, religion, and power on desert Arrakis.",
         collection="Collector Editions", year=1965),
    Book(id="b14", title="1984", author="George Orwell",
         price=349, original_price=549, rating=4.7, reviews=88300,
         cover=_cover("0451524934"), category="Classics",
         description="A dystopian masterpiece that redefined the genre.",
         collection="Collector Editions", year=1949),
    Book(id="b15", title="Pride and Prejudice", author="Jane Austen",
         price=299, original_price=499, rating=4.7, reviews=64200,
         cover=_cover("0141439513"), category="Classics",
         description="The eternal romance of Elizabeth and Mr. Darcy.",
         collection="Collector Editions", year=1813),
    Book(id="b16", title="The Way of Kings", author="Brandon Sanderson",
         price=899, original_price=1299, rating=4.9, reviews=41800,
         cover=_cover("0765326353"), category="Fantasy", badge="Collector",
         description="Epic fantasy on a scale rarely attempted — the Stormlight Archive begins.",
         collection="Collector Editions", year=2010),
    Book(id="b17", title="The Adventures of Huckleberry Finn",
         author="Mark Twain", price=349, original_price=499, rating=4.6,
         reviews=18400, cover=_cover("0142437174"), category="Adventure",
         description="A river journey and one of the great American novels.",
         collection="Collector Editions", year=1884),
    Book(id="b18", title="The Call of the Wild", author="Jack London",
         price=299, original_price=449, rating=4.6, reviews=27800,
         cover=_cover("0486264726"), category="Adventure",
         description="A sled dog's journey from domestication back to the wild.",
         collection="Collector Editions", year=1903),
    Book(id="b19", title="Gone Girl", author="Gillian Flynn",
         price=449, original_price=699, rating=4.6, reviews=35700,
         cover=_cover("0307588378"), category="Mystery",
         description="A marriage. A disappearance. A truth no one saw coming.",
         collection="Editor's Picks", year=2012),
    Book(id="b20", title="The Count of Monte Cristo", author="Alexandre Dumas",
         price=599, original_price=899, rating=4.8, reviews=44100,
         cover=_cover("0140449264"), category="Adventure", badge="Classic",
         description="Betrayal, escape, and the most patient revenge ever written.",
         collection="Collector Editions", year=1844),
    Book(id="b21", title="Harry Potter and the Sorcerer's Stone", author="J.K. Rowling",
         price=749, original_price=1099, rating=4.9, reviews=98400,
         cover=_cover("0590353403"), category="Fantasy", badge="Best Seller",
         description="The boy who lived — where the wizarding world begins.",
         collection="Editor's Picks", year=1997),
    Book(id="b22", title="The Alchemist", author="Paulo Coelho",
         price=399, original_price=599, rating=4.7, reviews=67300,
         cover=_cover("0062315005"), category="Adventure",
         description="A shepherd's journey to follow his Personal Legend.",
         collection="Award Winners", year=1988),
    Book(id="b23", title="To Kill a Mockingbird", author="Harper Lee",
         price=449, original_price=649, rating=4.8, reviews=74100,
         cover=_cover("0060935464"), category="Classics", badge="Award Winner",
         description="A story of justice, innocence, and moral courage in the Deep South.",
         collection="Award Winners", year=1960),
    Book(id="b24", title="The Great Gatsby", author="F. Scott Fitzgerald",
         price=349, original_price=549, rating=4.6, reviews=58900,
         cover=_cover("0743273567"), category="Classics",
         description="Jazz, longing, and the green light across the bay.",
         collection="Collector Editions", year=1925),
    Book(id="b25", title="Frankenstein", author="Mary Shelley",
         price=349, original_price=549, rating=4.6, reviews=39700,
         cover=_cover("0486282112"), category="Horror", badge="Classic",
         description="The creature, the creator, and the original gothic nightmare.",
         collection="Collector Editions", year=1818),
    Book(id="b26", title="A Game of Thrones", author="George R.R. Martin",
         price=799, original_price=1199, rating=4.8, reviews=81500,
         cover=_cover("0553103547"), category="Fantasy", badge="Collector",
         description="Winter is coming. The song of ice and fire begins.",
         collection="Collector Editions", year=1996),
    Book(id="b27", title="The Girl with the Dragon Tattoo", author="Stieg Larsson",
         price=549, original_price=799, rating=4.6, reviews=41700,
         cover=_cover("0307454541"), category="Mystery",
         description="A journalist, a hacker, and a forty-year-old disappearance.",
         collection="Editor's Picks", year=2005),
    Book(id="b28", title="The Da Vinci Code", author="Dan Brown",
         price=499, original_price=749, rating=4.5, reviews=69800,
         cover=_cover("0307474275"), category="Mystery", badge="Thriller",
         description="A murder in the Louvre and a trail of ancient secrets.",
         collection="New Releases", year=2003),
    Book(id="b29", title="The Martian", author="Andy Weir",
         price=549, original_price=849, rating=4.8, reviews=44200,
         cover=_cover("0553418025"), category="Sci-Fi",
         description="Stranded on Mars, one botanist refuses to die quietly.",
         collection="Editor's Picks", year=2011),
    Book(id="b30", title="Ender's Game", author="Orson Scott Card",
         price=499, original_price=749, rating=4.7, reviews=39400,
         cover=_cover("0812550706"), category="Sci-Fi", badge="Classic",
         description="A child genius trained for a war he doesn't understand.",
         collection="Collector Editions", year=1985),
    Book(id="b31", title="The Night Circus", author="Erin Morgenstern",
         price=579, original_price=849, rating=4.7, reviews=27600,
         cover=_cover("0307744434"), category="Romance",
         description="A duel of magic inside a circus that arrives without warning.",
         collection="New Releases", year=2011),
    Book(id="b32", title="It", author="Stephen King",
         price=699, original_price=999, rating=4.7, reviews=51300,
         cover=_cover("1501142976"), category="Horror", badge="Trending",
         description="Derry, Maine. A clown in the storm drain. It's back.",
         collection="New Releases", year=1986),
    Book(id="b33", title="Charlotte's Web", author="E.B. White",
         price=349, original_price=549, rating=4.8, reviews=41500,
         cover=_cover("0064400557"), category="Children", badge="Classic",
         description="Some pig. Terrific. Radiant. Humble. A friendship for the ages.",
         collection="Award Winners", year=1952),
    Book(id="b34", title="Percy Jackson: The Lightning Thief", author="Rick Riordan",
         price=449, original_price=649, rating=4.7, reviews=46700,
         cover=_cover("0786838655"), category="Children", badge="Best Seller",
         description="A demigod, a stolen lightning bolt, and a quest across America.",
         collection="Editor's Picks", year=2005),
    Book(id="b35", title="Norwegian Wood", author="Haruki Murakami",
         price=529, original_price=799, rating=4.6, reviews=24800,
         cover=_cover("0375704027"), category="Romance",
         description="A nostalgic story of loss, longing, and first love in Tokyo.",
         collection="Award Winners", year=1987),
    Book(id="b36", title="Matilda", author="Roald Dahl",
         price=379, original_price=599, rating=4.8, reviews=38200,
         cover=_cover("0142410373"), category="Children",
         description="A brilliant little girl with extraordinary powers and terrible parents.",
         collection="Editor's Picks", year=1988),
    Book(id="b37", title="Little Women", author="Louisa May Alcott",
         price=349, original_price=549, rating=4.7, reviews=38600,
         cover=_cover("0147514010"), category="Children",
         description="The March sisters — ambition, love, and growing up.",
         collection="Collector Editions", year=1868),
    Book(id="b38", title="Dracula", author="Bram Stoker",
         price=379, original_price=599, rating=4.6, reviews=33100,
         cover=_cover("0451530667"), category="Horror", badge="Classic",
         description="The gothic masterpiece that defined vampire fiction.",
         collection="Collector Editions", year=1897),
    Book(id="b39", title="The Shining", author="Stephen King",
         price=549, original_price=799, rating=4.7, reviews=48900,
         cover=_cover("0307743659"), category="Horror",
         description="An empty hotel, a snowed-in family, and something waking up.",
         collection="Editor's Picks", year=1977),
    Book(id="b40", title="Wonder", author="R.J. Palacio",
         price=449, original_price=699, rating=4.8, reviews=45900,
         cover=_cover("0375869026"), category="Children", badge="Best Seller",
         description="Choose kind. Auggie Pullman's unforgettable first year at school.",
         collection="Award Winners", year=2012),
]

BOOKS_BY_ID = {b.id: b for b in CATALOG}
